name       : haskell-directory
version    : 1.3.6.1
release    : 1
source     :
    - https://hackage.haskell.org/package/directory-1.3.6.1/directory-1.3.6.1.tar.gz : 7105a57ad248e3ce016936f0c3d0aca20393dfe648ca7df329b6ca0fb5169901
license    : BSD-3-Clause
component  : programming.haskell
summary    : Platform-agnostic library for filesystem operations
description: Platform-agnostic library for filesystem operations
networking : yes
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    autoconf -f -i
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
