name       : figlet
version    : 2.2.5
release    : 1
source     :
    - ftp://ftp.figlet.org/pub/figlet/program/unix/figlet-2.2.5.tar.gz : bf88c40fd0f077dab2712f54f8d39ac952e4e9f2e1882f1195be9e5e4257417d
license    : BSD-3-Clause
component  : desktop
summary    : 
    - FIGlet is the program for making large letters out of ordinary text
    - chkfont: a tool to check figlet font files for formatting errors
description: |
    - basically..
    _ _ _          _   _     _     
    | (_) | _____  | |_| |__ (_)___ 
    | | | |/ / _ \ | __| '_ \| / __|
    | | |   <  __/ | |_| | | | \__ \
    |_|_|_|\_\___|  \__|_| |_|_|___/
    - chkfont: a tool to check figlet font files for formatting errors
patterns   :
    - chkfont:
      - /usr/bin/chkfont
      - /usr/man/*/chkfont*
      - /usr/share/licenses/chkfont/*
      - /usr/share/figlet/figfont.txt

build      : |
    %make figlet DEFAULTFONTDIR=%PREFIX%/share/figlet/fonts
install    : |
    %make_install prefix=%PREFIX% DEFAULTFONTDIR=%PREFIX%/share/figlet/fonts
    install -D -m644 LICENSE "$installdir/usr/share/licenses/figlet/LICENSE"
    install -D -m644 LICENSE "$installdir/usr/share/licenses/chkfont/LICENSE"
    install -D -m644 figfont.txt "$installdir/usr/share/figlet/figfont.txt" 
check      : |
    %make check
