name       : gforth
version    : 0.7.3
release    : 1
source     :
    - http://mirror.rit.edu/gnu/gforth/gforth-0.7.3.tar.gz : 2f62f2233bf022c23d01c920b1556aa13eab168e3236b13352ac5e9f18542bb0
license    : GPL-3.0
component  : programming
homepage   : https://www.gnu.org/software/gforth/
summary    : Gforth is a fast and portable implementation of the ANS Forth language
description: |
  It works nicely with the Emacs editor, offers some nice features such as input completion and history, backtraces, a decompiler and a powerful locals facility, and it has a comprehensive manual.
  Gforth combines traditional implementation techniques with newer techniques for portability and performance.

setup      : |
    %configure
build      : |
    %make -j1
install    : |
    %make_install
check      : |
    %make check
    %make bench
