name       : pure
version    : 0.68
release    : 1
source     :
    - https://github.com/agraef/pure-lang/releases/download/pure-0.68/pure-0.68.tar.gz : cbc793490cc90e43218e177109e96ccaebf0380b39d8f2afb86b35b663e9a65f
    - https://github.com/agraef/pure-lang/releases/download/pure-0.68/pure-docs-0.68.tar.gz : a2a74fc17ca3bdde2b84fb1587b3fe145d5c7363bac1d79c54f5626dcf4cde94
license    : GPL-2.0-or-later # CHECK ME
component  : PLEASE FILL ME IN
summary    : PLEASE FILL ME IN
description: |
    PLEASE FILL ME IN
builddeps  :
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
