name       : haskell-hostname
version    : 1.0
release    : 1
source     :
    - https://hackage.haskell.org/package/hostname-1.0/hostname-1.0.tar.gz : 9b43dab1b6da521f35685b20555da00738c8e136eb972458c786242406a9cf5c
license    : BSD-3-Clause
component  : programming.haskell
summary    : A very simple package for determining the hostname
description: A very simple package for determining the hostname
networking : yes
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
